require_relative 'base_scraper_service/base_scraper'
require_relative 'base_scraper_service/agent_object'
require_relative 'base_scraper_service/location_service'
require_relative 'base_scraper_service/base'
